/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var tya=this||self,tyb=/^[\w+/_-]+[=]{0,2}$/,tyc=null,tyd=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&tyb.test(a)?a:""},tye=function(a,b){function c(){}c.prototype=b.prototype;a.V=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,f,h){for(var g=Array(arguments.length-2),e=2;e<arguments.length;e++)g[e-2]=arguments[e];return b.prototype[f].apply(d,g)}},tyf=function(a){return a};var tyg=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var tyh;var tyj=function(a,b){this.T=b===tyi?a:""},tyi={};var tyk=function(a,b){this.S=a;this.v=b;this.constructor.s||(this.constructor.s={});this.constructor.s[this.toString()]=this};tyk.prototype.toString=function(){this.u||(this.u=this.S.H+":"+this.v);return this.u};tyk.prototype.getType=function(){return this.v};var tyl=function(a,b){tyk.call(this,a,b)};tye(tyl,tyk);var tyn=function(a){tym.hasOwnProperty(a);this.H=a;tym[a]=this},tym;tym={};new tyn("lib");try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var ty=function(a){this.U=a};ty.prototype.toString=function(){return this.U};new ty("pVbxBc");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var tyo=new tyn("fva");new tyl(tyo,1);new ty("n73qwf");new ty("MpJwZc");new ty("UUJqVe");new ty("tdUkaf");new ty("fJuxOc");new ty("ZtVrH");new ty("WSziFf");new ty("ZmXAm");new ty("BWETze");new ty("UBSgGf");new ty("zZa4xc");new ty("o1bZcd");new ty("WwG67d");new ty("z72MOc");new ty("JccZRe");new ty("amY3Td");new ty("ABma3e");new ty("GHAeAc");new ty("gSshPb");new ty("klpyYe");new ty("OPbIxb");new ty("pg9hFd");new ty("Wt6vjf");new ty("yu4DA");new ty("vk3Wc");new ty("IykvEf");new ty("J5K1Ad");new ty("IW8Usd");new ty("IaqD3e");new ty("byfTOb");new ty("jbDgG");new ty("b8xKu");new ty("d0RAGb");
new ty("AzG0ke");new ty("J4QWB");new ty("LEikZe");new ty("rJmJrc");new ty("TuDsZ");new ty("hdXIif");new ty("mITR5c");new ty("DFElXb");new ty("NGntwf");new ty("Bgf0ib");new ty("Xpw1of");new ty("v5BQle");new ty("ofuapc");new ty("FENZqe");new ty("tLnxq");new ty("lsjVmc");new ty("a");var tyr=function(){this.g={b:"a",o:null,i:typ};this.j={b:"a",o:null,i:tyq}},tys=function(a){if(!a)throw Error();},typ=function(a,b){return a+"_"+b+".css"},tyq=function(a,b){return a+"_"+b+".js"};
tyr.prototype.load=function(){if(tyt(this.g)){var a=this.g.i(tyu(),tyv()),b=document.createElement("link");b.rel="stylesheet";b.type="text/css";b.href=a;document.head.appendChild(b)}if(tyt(this.j)){b=this.j.i(tyu(),tyv());var c=document;a="SCRIPT";"application/xhtml+xml"===c.contentType&&(a=a.toLowerCase());a=c.createElement(a);if(void 0===tyh){c=null;var d=tya.trustedTypes;if(d&&d.createPolicy)try{c=d.createPolicy("goog#html",{createHTML:tyf,createScript:tyf,createScriptURL:tyf})}catch(f){tya.console&&
tya.console.error(f.message)}tyh=c}b=(c=tyh)?c.createScriptURL(b):b;b=new tyj(b,tyi);a.src=b instanceof tyj&&b.constructor===tyj?b.T:"type_error:TrustedResourceUrl";(b=a.ownerDocument&&a.ownerDocument.defaultView)&&b!=tya?b=tyd(b.document):(null===tyc&&(tyc=tyd(tya.document)),b=tyc);b&&a.setAttribute("nonce",b);document.body.appendChild(a)}};
var tyu=function(){var a=window.location.pathname.substr(1);a="_generated_background_page.html"==a?"background":a.match(tyw)[1];var b=/^[\s\xa0]*$/;tys("string"==typeof a&&!b.test(a));return a},tyv=function(){return"ltr"==chrome.i18n.getMessage("@@bidi_dir")?"ltr":"rtl"},tyt=function(a){if("a"==a.b)return!0;if("n"==a.b)return!1;tys("s"==a.b);tys(Array.isArray(a.o));var b=tyu();return 0<=a.o.indexOf(b)},tyw=/(.+)\.html/;-1!=tyg(["miniplayer.html","settings.html"],tya.location.pathname.substr(1))&&("rtl"==("rtl"==chrome.i18n.getMessage("@@bidi_dir")?"rtl":"ltr")?tya.document.documentElement.setAttribute("dir","rtl"):tya.document.documentElement.setAttribute("dir","ltr"));var tyx=new tyr;tyx.g.i=function(a,b){return"ltr"==b?"css_compiled.css":"css_compiled_rtl.css"};tyx.g.b="s";tyx.g.o=["miniplayer","settings"];tyx.j.i=function(){return"main.js"};tyx.j.b="s";tyx.j.o=["miniplayer","settings"];tyx.load();
